stanfordnlp/pyvene

._init_log, .gitignore, models/gpt2/modelings_alignable_gpt2.py, models/modelings_alignable.py, run_alignment.py, trainer.py
This is for future experiments and makes this library easier to extend to other cases. Only minimum tests are done. Will fix issues if found.
=> add in gpt2 alignable, separate trainer/metrics

models/modelings_alignable.py
=> Add "LlamaForCausalLM" architecture name

models/alignable_base.py
Fix hook counters for non-generation calls by adding a flag to indicate whether we are in the "generate" call or not.
Similar to the hooks, this implementation can have unintended behavior if the program crashes in the middle of the generate call, which will leave the _is_generation to True. It would be great if we could find better indicators for the "generate" call.
=> Fix hook counters for non-generation calls.

models/interventions.py
Revised commit after fixing the code according to the comment.
=> Add SigmoidMaskRotatedSpaceIntervention

pyvene/models/interventions.py
Currently, we fix the boundary init to be `0.5` i.e., occupying half of the total dimension. This is not ideal. We now expose API to let users change.
=> allow dynamic boundary init for boundless das

pyvene/models/modeling_utils.py, tests/integration_tests/InterventionWithGPT2TestCase.py, tests/unit_tests/ModelUtilsTestCase.py
Only tested h, pos, and h.pos cases for now.
Also added some doc string to gather_neurons()
=> gather_neurons() unit tests

pyvene/models/modeling_utils.py, tests/unit_tests/ModelUtilsTestCase.py
First scatter_neurons() function tests. Will add more tests covering all cases of scatter() as that is more complicated than gather_neurons()
=> Add preliminary scatter() function tests

tests/unit_tests/ModelUtilsTestCase.py
This PR has an issue which I will comment below:
=> Add an extra test on scatter_neurons() testing case with no head.

pyvene/models/modeling_utils.py, requirements.txt, tests/unit_tests/ModelUtilsTestCase.py
Adapt modeling_utils with the new pyvene 101 colab - the new modeling_utils broke some items in pyvene 101.
=> [P1] Adaptive changes with pyvene 101 colab

tests/unit_tests/InterventionUtilsTestCase.py
Add intervention utils unit tests
Testing VanillaIntervention, CollectIntervention, BoundlessRotatedSpaceIntervention
=> [P1] Add intervention util unit tests

setup.py
This is to bump up our pip library version.
No testing is needed.
=> [Minor] Bump up pip version

pyvene/__init__.py, pyvene/models/intervenable_base.py, pyvene/models/interventions.py, tutorials/advanced_tutorials/IOI_with_Mask_Intervention.ipynb
Add in a baseline for trainable interventions. It learns a binary mask over representation, and the mask is used to choose the dimension to do intervention.
A tutorial is included.
=> [Minor] Add in trainable intervention based on binary mask intervention

tests/unit_tests/InterventionUtilsTestCase.py
Add trainable interventions tests with gradient flows
Test trainable interventions
=> [P1] Gradent interventions tests

pyvene/models/intervenable_base.py, pyvene/models/interventions.py
Allow gradient on the base input. Minor change on initial temp setting for intervention.
TBD
=> [Minor] Enable gradient for base inputs

pyvene/models/modeling_utils.py
The current model has bug in supporting new unseen model architecture. This change fixes the issue.
Default integration tests.
=> [P0] Fix unseen model type support

pyvene/models/intervenable_base.py
Create the `zero_grad()` function for intervenable model to make it compatible with external trainers (e.g., HF trainer).
Running default tests.
=> [Minor] Support zero_grad as a module

pyvene/models/intervenable_base.py
This is a basic support of loading in intervention weights with a non-static method.
[Manual testing]
=> [Minor] Loading interventions as non-static method

pyvene/models/intervenable_base.py
Exposing more APIs for loading and saving with trainable model components.
Nothing will be effected. Run P0 tests.
=> [Minor] Expose more APIs for loading and saving

README.md
=> [Minor] Update README.md with the correct citation link

CONTRIBUTING.md
=> [Minor] Update CONTRIBUTING.md

pyvene/models/intervenable_base.py, setup.py
Letting the forward API to accept the `labels` field.
Unit tests.
=> [Minor] Accepting `labels` field for loss calculation

pyvene/models/intervenable_modelcard.py
Issue ticket: https://github.com/stanfordnlp/pyvene/issues/138
Unit tests.
=> [P0] Adding back GPT2 and other model supports

setup.py
Version bump for another thing.
N.A.
=> [Minor] version bump

requirements.txt, tutorials/advanced_tutorials/Boundless_DAS.ipynb, tutorials/advanced_tutorials/tutorial_price_tagging_utils.py, tutorials/basic_tutorials/tutorial_intervention_training_utils.py
Removing `seaborn` dependency since it is not needed for the core setup.
Default tests.
=> [P0] removing seaborn dependency

pyvene/models/gemma/modelings_intervenable_gemma.py, pyvene/models/intervenable_modelcard.py, pyvene/models/mistral/modellings_intervenable_mistral.py
Added support for Gemma models and Llama for sequence classification.
Literally same interface as Llama.
=> [P1] Add Gemma + minor fixes

pyvene/models/layers.py
we might not need this as registering line below might trigger this call internally: https://github.com/pytorch/pytorch/blob/main/torch/nn/utils/parametrize.py#L421
kudos to peft library PR: https://github.com/huggingface/peft/pull/1657#discussion_r1570154894
N.A.
=> [Minor] Remove ortho init for DAS

setup.py
=> [Minor] Bump up version

pyvene/models/intervenable_base.py
Fix the base model use_cache arg passing
=> [Minor] Fix the base model use_cache arg passing

pyvene/models/intervenable_base.py
=> [Minor] Update  `use_cache` intervenable_base.py

pyvene/models/intervenable_modelcard.py, setup.py
Updating the import to bypass blip in case of failure
=> [Minor] Updating the import to bypass blip in case of failure

pyvene/models/intervenable_modelcard.py, pyvene/models/olmo/modelings_intervenable_olmo.py
Add OLMo models.
Tested locally.
=> [P2] Add OLMo models.

pyvene/models/interventions.py
Change the intervention output content. Probably need another fix to support any returning objects.
N.A.
=> [Minor] Fix intervention return objects

tutorials/basic_tutorials/Sparse_Autoencoder.ipynb
=> [Minor] Link fix

requirements.txt, tests/integration_tests/ComplexInterventionWithGPT2TestCase.py, tests/integration_tests/IntervenableBasicTestCase.py, tests/integration_tests/InterventionWithGPT2TestCase.py
Update the version requirement for transformers and its dependencies.
This allows using newer models such as Gemma-2 and Llama 3.1.
Local build & run.
=> [P1] Update the version requirement for transformers and its dependencies.

pyvene/models/gemma2/modelings_intervenable_gemma2.py
=> Fix mapping typo in modelings_intervenable_gemma2.py

setup.py
=> [Minor] Update setup.py

pyvene/models/intervenable_base.py
Remove additional printing statement.
N.A.
=> [Minor] Remove additional printing statement

pyvene/__init__.py
I added OLMo to pyvene init so I can "from pyvene import create_olmo" in my code
Tested locally.
=> [Minor] Add OLMo to pyvene init

pyvene/models/intervenable_base.py, tests/integration_tests/IntervenableBasicTestCase.py
Reverts stanfordnlp/pyvene#194. Something is broken here, will debug in a bit.
=> Revert "[Minor] Fix __str__ method in intervenable base model"

pyvene/models/intervenable_base.py, pyvene/models/interventions.py, pyvene/models/modeling_utils.py, tests/integration_tests/IntervenableBasicTestCase.py, tests/integration_tests/InterventionWithLlamaTestCase.py
Reverts stanfordnlp/pyvene#191
=> Revert "feat: add intervenable_model to forward's function signature"

pyvene/models/intervenable_base.py
Fix intervention loading device to default to cuda:0.
N.A.
=> [Minor] Fix intervention loading device to default to cuda:0

pyvene/models/intervenable_modelcard.py, pyvene/models/mllama/modelings_intervenable_mllama.py
I added the multimodal LLaMA model.
- created the mllama/modelings_intervenable_mllama.py file
- added the model to intervenable_modelcard.py.
Local runs.
=> [P2] Added Multimodal LLaMA (mllama)
