- pyvene/models/interventions.py
In line 265, there is a torch.arange(0, self.embed_dim). That will throw an error if self.embed_dim is None.
> Make self.embed_dim not None.

- README.md
- pyvene/models/basic_utils.py
- pyvene/models/intervenable_base.py
- tests/integration_tests/VanillaInterventionWithTransformerTestCase.py
Adding in a simple unit location broadcast for a simpler interface.
**Testing Done:**
```
WARNING:root:Saving trainable intervention to intkey_layer.0.repr.block_output.unit.pos.nunit.1#0.bin.
WARNING:root:Saving trainable intervention to intkey_layer.1.repr.block_output.unit.pos.nunit.1#0.bin.
.Removing testing dir ./test_output_dir_prefix-cc81c6
Removing testing dir ./test_output_dir_prefix-f082ae
Removing testing dir ./test_output_dir_prefix-48fe1d
Removing testing dir ./test_output_dir_prefix-5690bf
Removing testing dir ./test_output_dir_prefix-b9ec48
----------------------------------------------------------------------
Ran 26 tests in 3.628s
OK
```
> [Minor] add simple location broadcast for easy interface (#52)

- pyvene/models/configuration_intervenable_model.py
- pyvene/models/intervenable_base.py
- pyvene/models/intervention_utils.py
- pyvene/models/interventions.py
- pyvene/models/modeling_utils.py
- tests/integration_tests/InterventionWithGPT2TestCase.py
- tests/utils.py
Currently, we assume source representations are provided at runtime to do the intervention. This is not easy to swap like zero-out certain representations, adding some noise to certain representations, and swapping with a static yet trainable representation which is fixed for all examples.
We add in a new type of intervention, ConstantSourceIntervention for this line of interventions.
**Testing Done:**
```
WARNING:root:Loading trainable intervention from intkey_layer.1.repr.block_output.unit.pos.nunit.1#0.bin.
.Directory './test_output_dir_prefix-d86b4d' created successfully.
.Directory './test_output_dir_prefix-4bf335' created successfully.
WARNING:root:Saving trainable intervention to intkey_layer.0.repr.block_output.unit.pos.nunit.1#0.bin.
WARNING:root:Saving …
```
> [P1] Adding in constant source intervention support with new tests

- pyvene/__init__.py
- pyvene/models/configuration_intervenable_model.py
- pyvene/models/intervenable_base.py
- pyvene/models/intervention_utils.py
- pyvene/models/interventions.py
- tutorials/basic_tutorials/Load_Save_and_Share_Interventions.ipynb
Simplify generation intervention to have default mode of argument-less with just the base input. The default mode is inference-time intervention where we intervene on each decoding step now.
Cleanup intervention initialization with lazy dict variable passing, instead of hard coded arguments. Refactory existing code for readability.
**Testing Done:**
```  logging.warn(f"Loading trainable intervention from {binary_filename}.")
WARNING:root:Loading trainable intervention from intkey_layer.0.repr.block_output.unit.pos.nunit.1#0.bin.
WARNING:root:Loading trainable intervention from intkey_layer.1.repr.block_output.unit.pos.nunit.1#0.bin.
Directory './test_output_dir_prefix-9647b9' created successfully.
WARNING:root:Saving trainable intervention to …
```
> Model generation API simplified and cleanup tech debt on redundant variables

- pyvene/models/modeling_utils.py
Currently sorting thing does not work for path patching configs such as,
```py
def path_patching_config(
layer, stream="head_attention_value_output", num_layers=gpt.config.n_layer
):
intervening_component = [
IntervenableRepresentationConfig(layer, stream, "h.pos", group_key=0)
]
restoring_components = []
if not stream.startswith("mlp_"):
restoring_components += [
IntervenableRepresentationConfig(layer, "mlp_output", group_key=1)
]
for i in range(layer+1, num_layers):
restoring_components += [
IntervenableRepresentationConfig(i, "attention_output", group_key=1),
IntervenableRepresentationConfig(i, "mlp_output", group_key=1)
]
intervenable_config = IntervenableConfig(
intervenable_representations=intervening_component + restoring_components, …
```
> [Bug Fix] Topological order scoring is not accurate

- .github/pull_request_template.md
- pyvene/models/gpt2/modelings_intervenable_gpt2.py
- pyvene/models/intervenable_base.py
- pyvene/models/interventions.py
- pyvene_101.ipynb
- tests/integration_tests/InterventionWithMLPTestCase.py
- tutorials/advanced_tutorials/tutorial_ioi_utils.py
Currently, when using DAS with upstream interventions, gradient may throw arrow. This is due to some side-effect issues. We fix this by always-clone the passing activations in hook calls.
```
----------------------------------------------------------------------
Ran 49 tests in 43.641s
OK
```
> [Minor] Fix gradient backprop trainables with upstream interventions

- pyvene/models/intervenable_base.py
There was an autograd debugging line left in that significantly impacted performance. Discovered it while using a profiler to debug experiment speeds. Removing it reduced runtime for training my DAS benchmark work on `pythia-14m` from 289s to 170s!
No effect on library behaviours at all, just removed `torch.autograd.set_detect_anomaly(True)`.
> [P0] remove autograd debugging

- pyvene/models/intervenable_base.py
- pyvene/models/mlp/modelings_mlp.py
- pyvene/models/modeling_utils.py
- pyvene_101.ipynb
- setup.py
- tests/integration_tests/IntervenableBasicTestCase.py
- tests/unit_tests/InterventionUtilsTestCase.py
Currently, we expose the APIs in the way that prioritizes intervention serializations, which means we can only use intervention primitives defined in pyvene which limits customizable intervention types. Although people can define interventions as `nn.Modules`, it takes more efforts comparing to a simple function, or lambda expression. 
This change introduces how to interact with pyvene with a one-line lambda expression-based intervention which can also do trainable interventions with more customizable formats. At this point, pyvene basically acts like a `torch.hook` manager only losing its ability to share and save. Yet, it can easily support those simple interventions that are designed to be customizable.
```
grad_fn=<AddBackward0>) …
```
> [Minor] Adding support for any two-input lambda interventions; ResNet tutorials (no config)

- pyvene/__init__.py
- pyvene/models/blip/modelings_blip_itm.py
- pyvene/models/blip/modelings_intervenable_blip.py
- pyvene/models/blip/modelings_intervenable_blip_itm.py
- pyvene/models/intervenable_modelcard.py
Current BLIP implementation by @aryamanarora is for VQA, but our upcoming experiments with ColorSwap will require BLIP-ITM. I've added new model definition files specifically for the BLIP-ITM setup, as it's fairly different in architecture (vis enc -> text enc -> ITM head) from BLIP-VQA (vis enc -> text enc -> text dec). It's probably possible to capture both of them with a single general definition, but I wanted to take the lowest risk path for my first PR.
Haven't added any tests or done any testing yet. Just wanted to open a PR with the [mostly complete] work I've done already as it's Sunday night and I'm not sure when I'll be able to get back around to this next.
> [P1] Added BLIP-ITM model definitions

- pyvene/models/intervenable_base.py
- pyvene_101.ipynb
- tutorials/advanced_tutorials/Voting_Mechanism.ipynb
- tutorials/advanced_tutorials/tutorial_price_tagging_utils.py
Fix typos in the voting tutorial. The current intervention calls on generation has a buggy setup if we want to pass in a source and base to do interchange intervention. This is a quick fix but not the final solution.
Relevant tutorials are reran.
> [Minor] Fix typo in the voting tutorial; fix a bug in generation

- pyvene/models/modeling_utils.py
- pyvene_101.ipynb
Currently, the code assumes whenever we use customized function or lambda expression based interventions, we only allow two arguments. This. change allows us to specify the subspace for these interventions as well.
Ideally, the third argument could be anything for these customized interventions, which will be a future change.
Tutorial test is added.
> [Minor] Adding in subspace support for lambda

- pyvene/models/intervenable_base.py
- pyvene_101.ipynb
- tests/integration_tests/ComplexInterventionWithGPT2TestCase.py
- tests/integration_tests/InterventionWithMLPTestCase.py
The `forward()` and `generate()` call by default returns the output of unintervened model. This could cause slow down during training and inference. We disable them by default.
notebook is updated.
> [P1] Disable base output by default in fwd() and gen()

- README.md
- pyvene/models/intervenable_base.py
- pyvene/models/llama/modelings_intervenable_llama.py
- tutorials/basic_tutorials/Intervention_Training.ipynb
Currently `IntervenableModel.train()` and `IntervenableModel.evaluate()` are helper methods for training and evaluating interventions in a simple interface. I am renaming these to `train_alignment()` and `eval_alignment()` so that `train()` and `eval()` can set the model state (so that HF trainer can be compatible with this interface).
I think we have not actually been using these in `pyvene`-based projects because they don't allow much customisation so this doesn't break much; just had to change one notebook.
Tested in current project and worked. Let's see if tests pass!
> [P0] Rename train/evaluate methods so train/eval can set model state

- pyvene/models/intervenable_base.py
This adds the `named_parameters()` method which is used by HF trainer to find the trainable parameters to pass to the optimiser (#121).
No effect on any existing code.
> [P1] Add `IntervenableModel.named_parameters()`

- pyvene/models/intervenable_base.py
- pyvene_101.ipynb
In `generate()` call, we only pass in the `input_ids` field and rely on huggingface module to populate the attention mask fields. We now pass in the whole user input dict instead.
Tutorial test run passed.
> [Minor] Allow other field passing in generate besides input_ids

- pyvene/models/interventions.py
- pyvene/models/modeling_utils.py
- pyvene_101.ipynb
We added in `keep_last_dim` flag into intervention class to represent whether we want to intervene just on the last dimension without any reshaping.
- with this flag set to `False`, we will concatenate multiple reprs from different positions together and intervene on them as a unified repr.
- with this flag set to `True`, we intervene on them individually without concatenation. This allows an intervention to be shared across multiple positions easily.
Tutorial has a new test.
> [Minor] Allow sharing interventions across multiple positions

- pyvene/data_generators/causal_model.py
- setup.py
Small change that re-introduces input & output functions for pre-processing data when generating datasets from the causal model.
Only the `causal_model.py` file was edited.
Ran test cases for causal model (see screenshot below). Other tests aren't necessary because they aren't affected by `causal_model.py`. 
Tutorials using causal model run as expected since the update doesn't change the code's old behavior.
> [Minor] Revert CausalModel to accept input/output functions when generating factual/counterfactual datasets 

- pyvene/models/intervenable_base.py
Stored model type as `str` in the config dict. Necessary for `transformers` train loop checks.
Should have no effect on functionality.
> [P0] make sure config only has strs

- pyvene/models/intervenable_base.py
Added `use_cache` flag to forward call in `IntervenableModel`. This is necessary for DPO training with ReFT.
Ran all unit tests successfully. Logs attached below.
[unittest_logs.txt](https://github.com/stanfordnlp/pyvene/files/15181365/unittest_logs.txt)
> [Minor] Adding `use_cache` flag to intervenable model forward call

- pyvene/models/gemma/modelings_intervenable_gemma.py
- pyvene/models/gpt_neo/modelings_intervenable_gpt_neo.py
- pyvene/models/gpt_neox/modelings_intervenable_gpt_neox.py
- pyvene/models/llama/modelings_intervenable_llama.py
- pyvene/models/llava/modelings_intervenable_llava.py
- pyvene/models/mistral/modellings_intervenable_mistral.py
- tests/integration_tests/InterventionWithLlamaTestCase.py
- tests/utils.py
Fix the bug reported in #158 by modifying the modeling scripts of `gemma`, `gpt_neo`, `gpt_neox`, `llama`, `llava`, `mistral`, mainly involving three points:
- add the missed `split_head_and_permute` operation to split the hidden representations by attention heads
- fix the support of models with LM head (`_lm_type_to_module_mapping`), which missed elements in `v[1:]`
- add the support of grouped query attention modules used by Llama-like models
All tests passed.
```
'pyvene' is not installed.
PASS: pyvene is not installed. Testing local dev code.
=== Test Suite: VanillaInterventionWithTransformerTestCase ===
loaded model
./shared/nas2/wangxz/pyvene/pyvene/models/intervenable_base.py:55: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
logging.warn( …
```
> [Bug-Fix] fix attention head intervention for multiple models

- pyvene/__init__.py
- pyvene/models/configuration_intervenable_model.py
- pyvene/models/intervenable_base.py
- pyvene/models/interventions.py
- pyvene/models/layers.py
Add an `AutoencoderLayer` and an `AutoencoderIntervention` to support interpretability methods that use autoencoders to learn interpretable feature space, including Sparse Autoencoders.
* The `AutoencoderLayer` defines any autoencoder with a single-layer encoder and a single-layer decoder. Users can additionally define customized autoencoders by extending the base class `AutoencoderLayerBase`.
* The `AutoencoderIntervention` defines an intervention that allows interchange interventions in the latent space of the autoencoder.
The `AutoencoderIntervention` supports loading pre-trained autoencoders trained outside `pyvene` framework, with the `get_intervenable_with_autoencoder` function below:
```python
def get_intervenable_with_autoencoder(
model, autoencoder, intervention_dimensions, …
```
> [P2] Add Sparse Autoencoder Interventions

- pyvene/models/intervenable_base.py
- pyvene_101.ipynb
- requirements.txt
Recent SAE change causes a regression for some existing tests. This change tries to fix the issue by reverting back some code change.
Running existing tests.
> [P0] Revert back the kwargs argument for intervention init

- README.md
- pyvene/__init__.py
- pyvene/models/intervenable_base.py
- pyvene/models/modeling_utils.py
- pyvene_101.ipynb
- requirements.txt
**This is only the first code change to support NDIF infra in pyvene.** Multiple changes are needed to fully support NDIF backend in pyvene. Here, we will describe the overall goal of these changes.
[NDIF](https://ndif.us/) project aims to provide a **remote service** for doing intervened model inference so that users do not have to host their own models. With these change, users can wrap NDIF model as an intervenable model and potentially run the intervened model inference remotely by leveraging on the NDIF infrastature. 
We will provide two ways of model wrapping:
(recommended way)
```py
from nnsight import LanguageModel
gpt2_ndif = LanguageModel('openai-community/gpt2', device_map='cpu')
pv_config = pv.IntervenableConfig({
"component": "transformer.h[0].attn.output",
"intervention": …
```
> [P0] First infrastructure change to support NDIF backend

- pyvene/models/intervenable_base.py
Add saving/loading of trainable parameters in the model (e.g. classification heads) to `IntervenableModel.save()` and `IntervenableModel.load()`. Draft PR since some tests are failing, will finalise tomorrow.
Saving/loading of Gemma 2B-IT for sequence classification works perfectly.
> [P2] Save/load trainable params in `IntervenableBase` methods

- pyvene/models/modeling_utils.py
In `modeling_utils.py`, there is a part of the code that causes error when using GPU. It seems that it's because the `unit_locations` variable was forced to be in cpu.
No test done yet, just to flag the issue and to raise the attention of the main contributors
> device of unit_locations should follow tensor_input

- pyvene/models/intervenable_base.py
Details: https://github.com/stanfordnlp/pyvene/issues/163
Unit tests running.
> [Minor] Fix use_cache flag propagation

- pyvene/__init__.py
- pyvene/models/intervenable_base.py
- pyvene/models/interventions.py
- pyvene/models/modeling_utils.py
This is the first change to support more generic intervention output formatting. And this change also serves the purpose of enabling this library to support more generic adaptor-like tuning.
N.A.
> [Minor] Start to support generic intervention output, and adaptor-like tuning

- pyvene/models/intervenable_base.py
Add simple (and naive) for dictionary output of modules. Similar to how `tuples`s were dealt with, I just select the first value of the dict. Only made changes to `BaseModel`. I'm not yet super familiar with the code so there might be some other modification needed.
It works with my model which has module dict outputs (for ZeroIntervention and LoreftIntervention). Didn't do extensive testing as this felt quite straightforward.
> add support for dict outputs (select the first value)

- requirements.txt
Updating the version to avoid the following error:
```
RuntimeError: Failed to import transformers.models.blip.modeling_blip because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/usr/local/lib/python3.10/site-packages/huggingface_hub/__init__.py)
```
> [Minor] Update the huggingface-hub version

- pyvene/models/intervenable_base.py
- requirements.txt
- setup.py
Cleanup some dependency stuff.
N.A.
> [Minor] Update dependency

- pyvene/__init__.py
- pyvene/models/interventions.py
- tutorials/basic_tutorials/Sparse_Autoencoder.ipynb
> [Minor] Adding interchange intervention for SAEs

- pyvene/models/gemma2/modelings_intervenable_gemma2.py
- pyvene/models/intervenable_modelcard.py
> [P2] Add Gemma 2 model

- pyvene/models/gpt2/modelings_intervenable_gpt2.py
- pyvene_101.ipynb
Fix Pyvene 101 by prohibiting SDPA Attention Use
- [] I have attached the testing log above
- [] I have changed documentations
- [] I have added tests for my changes
> [P0] Prohibit SDPA Attention Use in Pyvene

- pyvene/models/intervenable_base.py
- pyvene_101.ipynb
- tests/utils.py
Fix HF/transformers version change issues due to #201 
> [P0] Fix test failures due to transformers version change

- pyvene/models/esm/modelings_intervenable_esm.py
- pyvene/models/intervenable_modelcard.py
Add ESM models.
Tested locally.
- [ x] My PR title strictly follows the format: `[Your Priority] Your Title`
- [x ] I provide enough comments to my code
> [P2] Add ESM models

- pyvene/models/intervenable_base.py
- tests/integration_tests/IntervenableBasicTestCase.py
Currently when we print or stringify a model, it usually throws an error because the __str__ method tries to use an attribute of the class (`intervention_types`) that does not exist. This replaces that with the correct way to get intervention types, so that printing out the model (and converting it to a string) works.
Used this small script:
```
import torch
import pyvene as pv
_, tokenizer, gpt2 = pv.create_gpt2()
config = pv.IntervenableConfig({
"layer": 0,
"component": "mlp_input"},
pv.AdditionIntervention
)
pv_gpt2 = pv.IntervenableModel(config, model=gpt2)
print(pv_gpt2)
```
On the base version, the output is an exception:
```
nnsight is not detected. Please install via 'pip install nnsight' for nnsight backend.
/nlp/scr/ram1998/miniconda3/envs/pyreft_dev/lib/python3.12/site-packages/ …
```
> [Minor] Fix __str__ method in intervenable base model

- pyvene/models/blip/modelings_intervenable_blip.py
- pyvene/models/blip/modelings_intervenable_blip_itm.py
- `block_output` now correctly maps to `CONST_OUTPUT_HOOK` instead of `CONST_INPUT_HOOK` in `modelings_intervenable_blip.py` & `modelings_intervenable_blip_itm.py`
> [Bug Fix] Fix BLIP output hook

- pyvene/models/intervenable_base.py
- pyvene/models/interventions.py
- pyvene/models/modeling_utils.py
- tests/integration_tests/IntervenableBasicTestCase.py
- tests/integration_tests/InterventionWithLlamaTestCase.py
Added the `intervenable_model` parameter to the forward function signature, enabling user-defined intervention classes to have direct access to the model instance. This allows for more advanced manipulations such as using `intervenable_model.model.lm_head(base)` to interact with lower-level model components.
Tested the changes locally by defining custom intervention classes that access the model's internal components, including the `lm_head`. Verified that these interventions function as expected during model execution.
> feat: add intervenable_model to forward's function signature

- pyvene/models/intervenable_base.py
The `logger.warn` method is deprecated so the library throws different deprecation warning: 
```python
/home/runner/work/pyvene/pyvene/pyvene/models/intervenable_base.py:72: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
```
It also fixes a few typos along the way.
Run tests.
> [Minor] Migrate to `logger.warning` usage

- pyvene/models/olmo/modelings_intervenable_olmo.py
Previously revision would only be used if a config was specified to create an olmo model, this line also adds that support when a config is not specified.
Checked that revision model was actually used instead of the main model.
> [Minor] Add revision to olmo creation function
